# Site settings
title: thejustinwalsh LLC
email: contact.me@thejustinwalsh.com
description: > # this means to ignore newlines until "baseurl:"
  The official corner of the internet for thejustinwalsh. Catch
  the blog, check out the projects, and contact for hire.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://thejustinwalsh.github.io" # the base hostname & protocol for your site
twitter_username: thejustinwalsh
github_username:  thejustinwalsh

# Build settings
markdown: kramdown

# Prose.io
prose:
  rooturl: '_posts'
  siteurl: 'http://thejustinwalsh.github.io/'
  relativeLinks: 'http://prose.github.io/starter/links.jsonp'
  media: 'media'
  ignore:
    - index.md
    - _config.yml
    - /_layouts
    - /_includes
  metadata:
    _posts:
      - name: "layout"
        field:
          element: "hidden"
          value: "post"
      - name: "tags"
        field:
          element: "multiselect"
          label: "Add Tags"
          placeholder: "Choose Tags"
          options:
            - name: "News"
              value: "news"
            - name: "C++"
              value: "cpp"
            - name: "Unreal Engine"
              value: "ue4"

