# Site settings
title: thejustinwalsh LLC
email: contact.me@thejustinwalsh.com
description: > # this means to ignore newlines until "baseurl:"
  The official corner of the internet for thejustinwalsh. Catch
  the blog, check out the projects, and contact for hire.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://thejustinwalsh.com" # the base hostname & protocol for your site
twitter_username: thejustinwalsh
github_username:  thejustinwalsh

# Build settings
markdown: kramdown
